services:
  postgres:
    image: postgres:13.3-alpine3.14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-app}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:5.5
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    logging:
      driver: none

  restmock:
    image: node:14.17.4-buster-slim
    ports:
      - "3000:3000"
      - "3001:3001"
    init: true
    working_dir: /mam/aspirity/restmock
    volumes:
      - ../../:/mam
    depends_on:
      - postgres
    environment:
      PORT: "3000"
      ASPIRITY_RESTMOCK_SERVER_PORT: "3001"
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-changeme}@postgres:5432/${POSTGRES_DB:-app}
    command: node --enable-source-maps ./-/node.js --start
#   sync:
#     build: .
#     container_name: sync_container
#     environment:
#       DATABASE_URL: ${DATABASE_URL:-postgres://postgres:changeme@postgres:5432/app}
#       PORT: ${PORT:-3000}
#       IP: 0.0.0.0
#     ports:
#       - 3000:3000
#       - 5858:5858
#     volumes:
#       - ./node_modules:/usr/src/app
#     networks:
#       - postgres
#     restart: unless-stopped
#     command: yarn start

volumes:
  pgadmin: {}
  postgres: {}
